# Generated by Django 3.2.5 on 2021-07-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeones',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('idchamp', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('iditem', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_summon', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('accountId', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('ligaS', models.CharField(max_length=20)),
                ('ligaF', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Min',
            fields=[
                ('min', models.IntegerField(primary_key=True, serialize=False)),
                ('farmMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sumonerspells',
            fields=[
                ('nombre', models.CharField(max_length=10)),
                ('idspell', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=50)),
                ('servidor', models.CharField(choices=[('la2', 'LAS'), ('la1', 'LAN')], max_length=6)),
                ('invocador', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Pvision', models.IntegerField()),
                ('pinks', models.IntegerField()),
                ('KDA', models.CharField(max_length=100)),
                ('minutos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.min')),
            ],
        ),
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('idGame', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idSummon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLiga', models.CharField(max_length=25)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.rol')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='summon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.usuario'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KDA', models.CharField(max_length=100)),
                ('Farmxmin', models.FloatField()),
                ('lane', models.CharField(max_length=15)),
                ('vision', models.IntegerField()),
                ('pinks', models.IntegerField()),
                ('idSpell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.sumonerspells')),
                ('idchamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.campeones')),
                ('idgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.partidas')),
                ('iditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academica.items')),
            ],
        ),
    ]
