# Generated by Django 3.2.5 on 2021-07-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='campeones',
            name='idchamp',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sumonerspells',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
