# Generated by Django 3.2.5 on 2021-07-17 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0002_auto_20210717_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='idSpell',
        ),
        migrations.RemoveField(
            model_name='game',
            name='idchamp',
        ),
        migrations.RemoveField(
            model_name='game',
            name='iditem',
        ),
    ]
