# Generated by Django 3.2.5 on 2021-07-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0003_auto_20210717_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='servidor',
            field=models.CharField(max_length=6),
        ),
    ]
