# Generated by Django 3.2.5 on 2021-07-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0004_alter_usuario_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='servidor',
            field=models.CharField(choices=[('la2', 'LAS'), ('la1', 'LAN')], max_length=6),
        ),
    ]
