# Generated by Django 3.2.5 on 2021-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0005_alter_usuario_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='level',
            field=models.IntegerField(),
        ),
    ]
