# Generated by Django 3.2.5 on 2021-07-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0007_alter_usuario_servidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='minutos',
        ),
        migrations.AddField(
            model_name='game',
            name='campeon',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='items',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='spells',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Min',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
