# Generated by Django 3.2.5 on 2021-07-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0008_auto_20210718_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='campeon',
        ),
        migrations.RemoveField(
            model_name='game',
            name='items',
        ),
        migrations.RemoveField(
            model_name='game',
            name='spells',
        ),
    ]
